apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: "nginx"                     # use your ingress class
    nginx.ingress.kubernetes.io/enable-cors: "true"          # enable CORS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"       # allow all origins
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.didin.in
      secretName: api-didin-tls
  rules:
    - host: api.didin.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
    - host: sonu.didin.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 5000

