FROM node:20-bullseye

WORKDIR /app

# Install bash (optional but helps)
RUN apk add --no-cache bash

COPY package.json package-lock.json ./

# Install dependencies
RUN npm cache clean --force \
 && npm install

COPY . .

# Fix Vite permission issue
RUN chmod -R 777 /app/node_modules/.bin

# Build Vite app (creates dist/)
RUN npm run build

EXPOSE 5000

# Serve build folder on port 5000
CMD ["npm", "run", "preview", "--", "--host", "--port", "5000"]
